apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: localsre
  labels:
    app.kubernetes.io/name: localsre-api
    app.kubernetes.io/component: backend
data:
  APP_NAME: "LocalSRE API"
  ENVIRONMENT: "k8s-local"
  PORT: "8000"
  ENABLE_METRICS: "true"
  ENABLE_CHAOS_ENDPOINTS: "true"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "localsredb"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
