apiVersion: v1
kind: Service
metadata:
  name: localsre-api
  namespace: localsre
  labels:
    app.kubernetes.io/name: localsre-api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: localsre-api
